# Generated by Django 4.1 on 2022-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='game',
        ),
        migrations.AddField(
            model_name='collection',
            name='game',
            field=models.ManyToManyField(to='collection.games'),
        ),
    ]
